/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HireRouteImport } from './routes/hire'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as ArticlesTagsTagRouteImport } from './routes/articles/tags/$tag'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HireRoute = HireRouteImport.update({
  id: '/hire',
  path: '/hire',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesTagsTagRoute = ArticlesTagsTagRouteImport.update({
  id: '/articles/tags/$tag',
  path: '/articles/tags/$tag',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/hire': typeof HireRoute
  '/resume': typeof ResumeRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/articles/tags/$tag': typeof ArticlesTagsTagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/hire': typeof HireRoute
  '/resume': typeof ResumeRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/articles/tags/$tag': typeof ArticlesTagsTagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/hire': typeof HireRoute
  '/resume': typeof ResumeRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/articles/tags/$tag': typeof ArticlesTagsTagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/hire'
    | '/resume'
    | '/articles/$slug'
    | '/projects/$slug'
    | '/articles/'
    | '/projects/'
    | '/articles/tags/$tag'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/hire'
    | '/resume'
    | '/articles/$slug'
    | '/projects/$slug'
    | '/articles'
    | '/projects'
    | '/articles/tags/$tag'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/hire'
    | '/resume'
    | '/articles/$slug'
    | '/projects/$slug'
    | '/articles/'
    | '/projects/'
    | '/articles/tags/$tag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  HireRoute: typeof HireRoute
  ResumeRoute: typeof ResumeRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ArticlesTagsTagRoute: typeof ArticlesTagsTagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire': {
      id: '/hire'
      path: '/hire'
      fullPath: '/hire'
      preLoaderRoute: typeof HireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/tags/$tag': {
      id: '/articles/tags/$tag'
      path: '/articles/tags/$tag'
      fullPath: '/articles/tags/$tag'
      preLoaderRoute: typeof ArticlesTagsTagRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  HireRoute: HireRoute,
  ResumeRoute: ResumeRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ArticlesTagsTagRoute: ArticlesTagsTagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
