/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HireRouteImport } from './routes/hire'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as AdminArticlesIndexRouteImport } from './routes/admin/articles/index'
import { Route as AdminArticlesNewRouteImport } from './routes/admin/articles/new'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects/index'
import { Route as AdminProjectsNewRouteImport } from './routes/admin/projects/new'
import { Route as ArticlesTagsTagRouteImport } from './routes/articles/tags/$tag'
import { Route as AdminArticlesEditIdRouteImport } from './routes/admin/articles/edit.$id'
import { Route as AdminProjectsEditIdRouteImport } from './routes/admin/projects/edit.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HireRoute = HireRouteImport.update({
  id: '/hire',
  path: '/hire',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesIndexRoute = AdminArticlesIndexRouteImport.update({
  id: '/admin/articles/',
  path: '/admin/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesNewRoute = AdminArticlesNewRouteImport.update({
  id: '/admin/articles/new',
  path: '/admin/articles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/admin/projects/',
  path: '/admin/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsNewRoute = AdminProjectsNewRouteImport.update({
  id: '/admin/projects/new',
  path: '/admin/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesTagsTagRoute = ArticlesTagsTagRouteImport.update({
  id: '/articles/tags/$tag',
  path: '/articles/tags/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesEditIdRoute = AdminArticlesEditIdRouteImport.update({
  id: '/admin/articles/edit/$id',
  path: '/admin/articles/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsEditIdRoute = AdminProjectsEditIdRouteImport.update({
  id: '/admin/projects/edit/$id',
  path: '/admin/projects/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/hire': typeof HireRoute
  '/resume': typeof ResumeRoute
  '/admin/login': typeof AdminLoginRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/articles/tags/$tag': typeof ArticlesTagsTagRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/articles/edit/$id': typeof AdminArticlesEditIdRoute
  '/admin/projects/edit/$id': typeof AdminProjectsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/hire': typeof HireRoute
  '/resume': typeof ResumeRoute
  '/admin/login': typeof AdminLoginRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/articles/tags/$tag': typeof ArticlesTagsTagRoute
  '/admin/articles': typeof AdminArticlesIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/articles/edit/$id': typeof AdminArticlesEditIdRoute
  '/admin/projects/edit/$id': typeof AdminProjectsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/hire': typeof HireRoute
  '/resume': typeof ResumeRoute
  '/admin/login': typeof AdminLoginRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/articles/tags/$tag': typeof ArticlesTagsTagRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/articles/edit/$id': typeof AdminArticlesEditIdRoute
  '/admin/projects/edit/$id': typeof AdminProjectsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/hire'
    | '/resume'
    | '/admin/login'
    | '/articles/$slug'
    | '/projects/$slug'
    | '/admin/'
    | '/articles/'
    | '/projects/'
    | '/admin/articles/new'
    | '/admin/projects/new'
    | '/articles/tags/$tag'
    | '/admin/articles/'
    | '/admin/projects/'
    | '/admin/articles/edit/$id'
    | '/admin/projects/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/hire'
    | '/resume'
    | '/admin/login'
    | '/articles/$slug'
    | '/projects/$slug'
    | '/admin'
    | '/articles'
    | '/projects'
    | '/admin/articles/new'
    | '/admin/projects/new'
    | '/articles/tags/$tag'
    | '/admin/articles'
    | '/admin/projects'
    | '/admin/articles/edit/$id'
    | '/admin/projects/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/hire'
    | '/resume'
    | '/admin/login'
    | '/articles/$slug'
    | '/projects/$slug'
    | '/admin/'
    | '/articles/'
    | '/projects/'
    | '/admin/articles/new'
    | '/admin/projects/new'
    | '/articles/tags/$tag'
    | '/admin/articles/'
    | '/admin/projects/'
    | '/admin/articles/edit/$id'
    | '/admin/projects/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  HireRoute: typeof HireRoute
  ResumeRoute: typeof ResumeRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  AdminArticlesNewRoute: typeof AdminArticlesNewRoute
  AdminProjectsNewRoute: typeof AdminProjectsNewRoute
  ArticlesTagsTagRoute: typeof ArticlesTagsTagRoute
  AdminArticlesIndexRoute: typeof AdminArticlesIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  AdminArticlesEditIdRoute: typeof AdminArticlesEditIdRoute
  AdminProjectsEditIdRoute: typeof AdminProjectsEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire': {
      id: '/hire'
      path: '/hire'
      fullPath: '/hire'
      preLoaderRoute: typeof HireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles/': {
      id: '/admin/articles/'
      path: '/admin/articles'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AdminArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles/new': {
      id: '/admin/articles/new'
      path: '/admin/articles/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AdminArticlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/admin/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/new': {
      id: '/admin/projects/new'
      path: '/admin/projects/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AdminProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/tags/$tag': {
      id: '/articles/tags/$tag'
      path: '/articles/tags/$tag'
      fullPath: '/articles/tags/$tag'
      preLoaderRoute: typeof ArticlesTagsTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles/edit/$id': {
      id: '/admin/articles/edit/$id'
      path: '/admin/articles/edit/$id'
      fullPath: '/admin/articles/edit/$id'
      preLoaderRoute: typeof AdminArticlesEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/edit/$id': {
      id: '/admin/projects/edit/$id'
      path: '/admin/projects/edit/$id'
      fullPath: '/admin/projects/edit/$id'
      preLoaderRoute: typeof AdminProjectsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  HireRoute: HireRoute,
  ResumeRoute: ResumeRoute,
  AdminLoginRoute: AdminLoginRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  AdminArticlesNewRoute: AdminArticlesNewRoute,
  AdminProjectsNewRoute: AdminProjectsNewRoute,
  ArticlesTagsTagRoute: ArticlesTagsTagRoute,
  AdminArticlesIndexRoute: AdminArticlesIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  AdminArticlesEditIdRoute: AdminArticlesEditIdRoute,
  AdminProjectsEditIdRoute: AdminProjectsEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
